version: '3.3'

services:
  ryder:
    container_name: ryder
    hostname: ryder
    image: ryder:latest
    build:
      context: ./ryder
    ports:
      - "3000:3000"
    environment:
      - JAVAS_PORT=5000
      - CS_PORT=5001
      - PYS_PORT=5002
    links:
      - java-service
      - c-service
      - python-service
  java-service:
    container_name: java-service
    hostname: java-service
    image: ryderjava:latest
    environment:
      - PORT=5000
    expose:
      - "5000"
    build:
      context: ./workers/javac
  c-service:
    container_name: c-service
    hostname: c-service
    image: ryderc:latest
    environment:
      - PORT=5001
    expose:
      - "5001"
    build:
      context: ./workers/c
  python-service:
    container_name: python-service
    hostname: python-service
    image: ryderpy:latest
    environment:
      - PORT=5002
    expose:
      - "5002"
    build:
      context: ./workers/python
  php-service:
    container_name: php-service
    hostname: php-service
    image: ryderphp:latest
    environment:
      - PORT=5003
    expose:
      - "5003"
    build:
      context: ./workers/php
  ruby-service:
    container_name: ruby-service
    hostname: ruby-service
    image: ryderruby:latest
    environment:
      - PORT=5004
    expose:
      - "5004"
    build:
      context: ./workers/ruby
