version: '3.3'

services:

  ryder:
    image: ryder:latest
    ports:
      - "3000:3000"
    environment:
      - JAVAS_PORT=5000
      - CS_PORT=5001
      - PYS_PORT=5002
    deploy:
      replicas: 1

  java-service:
    image: ryderjava:latest
    environment:
      - PORT=5000
    expose:
      - "5000"
    deploy:
      replicas: 1

  c-service:
    image: ryderc:latest
    environment:
      - PORT=5001
    expose:
      - "5001"
    deploy:
      replicas: 1

  python-service:
    image: ryderpy:latest
    environment:
      - PORT=5002
    expose:
      - "5002"
    deploy:
      replicas: 1

  php-service:
    image: ryderphp:latest
    environment:
      - PORT=5003
    expose:
      - "5003"
    deploy:
      replicas: 1

  ruby-service:
    image: ryderruby:latest
    environment:
      - PORT=5004
    expose:
      - "5004"
    deploy:
      replicas: 1